---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: apps-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: ealen/echo-server:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: apps-plane
spec:
  type: ClusterIP
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-route
  namespace: apps-plane
spec:
  parentRefs:
    - name: apisix
      namespace: platform-plane
  hostnames:
    - "test.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: echo
          namespace: apps-plane
          port: 80